
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DASCII = 28;
  public static final int DBYTE = 29;
  public static final int DSPACE = 32;
  public static final int ISINGREGOP = 25;
  public static final int RMDOPER = 11;
  public static final int STRLITERAL = 33;
  public static final int LPAREN = 7;
  public static final int JALR = 20;
  public static final int RTFOPER = 13;
  public static final int IBRANCHOP = 24;
  public static final int REG = 34;
  public static final int IMEMOPER = 23;
  public static final int RPAREN = 8;
  public static final int DASCIIZ = 27;
  public static final int STARTTEXT = 6;
  public static final int ROPER = 10;
  public static final int NOP = 21;
  public static final int COMMA = 3;
  public static final int RTTOPER = 14;
  public static final int RSOPER = 12;
  public static final int EOL = 2;
  public static final int ERET = 19;
  public static final int DWORD = 31;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int JOPER = 26;
  public static final int IMM = 35;
  public static final int BREAK = 17;
  public static final int COLON = 4;
  public static final int STARTDATA = 5;
  public static final int RJROPER = 16;
  public static final int SYSCALL = 18;
  public static final int IOPER = 22;
  public static final int LABEL = 9;
  public static final int DHALFWORD = 30;
  public static final int RSPOPER = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EOL",
  "COMMA",
  "COLON",
  "STARTDATA",
  "STARTTEXT",
  "LPAREN",
  "RPAREN",
  "LABEL",
  "ROPER",
  "RMDOPER",
  "RSOPER",
  "RTFOPER",
  "RTTOPER",
  "RSPOPER",
  "RJROPER",
  "BREAK",
  "SYSCALL",
  "ERET",
  "JALR",
  "NOP",
  "IOPER",
  "IMEMOPER",
  "IBRANCHOP",
  "ISINGREGOP",
  "JOPER",
  "DASCIIZ",
  "DASCII",
  "DBYTE",
  "DHALFWORD",
  "DWORD",
  "DSPACE",
  "STRLITERAL",
  "REG",
  "IMM"
  };
}

